server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://191.234.196.75:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: prueba-service
          uri: lb://custom-service
          predicates:
            - Path=/prueba/**
